import { Poppins } from 'next/font/google';
import Header from '@/components/header';
import '../assets/styles/global.css';
import { ModalProvider } from '@/contexts/Modal/modal.context';
import Modal from '@/contexts/Modal';

const poppins = Poppins({
	subsets: ['latin'],
	weight: [
		'100',
		'200',
		'300',
		'400',
		'500',
		'600',
		'700',
		'800',
		'900',
	],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${poppins.className} flex flex-col body-container z-0`}
			>
				<ModalProvider>
					<Modal />
					<Header />
					<div className='-top-48 relative'>{children}</div>
				</ModalProvider>
			</body>
		</html>
	);
}
